/** @babel */
import {
    DECLARATION_HANDLER_PROPERTY,
    LEXICAL_HANDLER_PROPERTY,
    NAMESPACES_FEATURE,
    NAMESPACE_PREFIXES_FEATURE,
    VALIDATION_FEATURE,
    APACHE_SCHEMA_VALIDATION_FEATURE,
    APACHE_DYNAMIC_VALIDATION_FEATURE,
    InputSource,
    DefaultHandler,
    SaxDriver} from './lib/sax2';

export {
    DECLARATION_HANDLER_PROPERTY,
    LEXICAL_HANDLER_PROPERTY,
    NAMESPACES_FEATURE,
    NAMESPACE_PREFIXES_FEATURE,
    VALIDATION_FEATURE,
    APACHE_SCHEMA_VALIDATION_FEATURE,
    APACHE_DYNAMIC_VALIDATION_FEATURE,
    InputSource,
    DefaultHandler,
    SaxDriver
}
